// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxswxteqcyazvxfwgcxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4c3d4dGVxY3lhenZ4ZndnY3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNDIzNTEsImV4cCI6MjA3NDkxODM1MX0.oFzGmfJxMb8upSNAYfFw3QuPS5Hk4Myf1QafpwkOcK8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});