// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzjtdlvebqrglfbaurza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56anRkbHZlYnFyZ2xmYmF1cnphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDA0MzEsImV4cCI6MjA3Mzg3NjQzMX0.KtWM5WWTA8uAcYJpopXUWe1FTewdmBbqWwl5QPXA4Yo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});